### ISSUE TITLE
[Bug]: 600. 설문조사 > 설문참여 등록 오류

### ISSUE THREAD

**Issue by danheean** [eGovFramework/egovframe-common-components#242]
### 연락처 Contact

danhee.an@gmail.com

### 오류 내용 Error Description

오류를 발견했어요. I found an error.

Mysql jdbc driver 8.0.x를 사용할 경우 설문조사 > 설문참여 등록 화면에서 데이터처리 에러 발생

이전 버전 5.1.49를 사용하면 정상으로 구동합니다.

### 오류 재현 방법 How to reproduce the error

(다음은 예시이며, 내용을 덮어 써 주세요. The following is an example, please overwrite the content.)

 1. 업무담당자 TEST1로 로그인한다.
![image](https://github.com/eGovFramework/egovframe-common-components/assets/21186414/fffe7b1d-2b57-467f-8051-3d1fefb75eb8)
 2. 600.설문조사 메뉴를 클릭한다. (설문 및 설문템플릿이 미리 등록되어 있어야 합니다.)
![image](https://github.com/eGovFramework/egovframe-common-components/assets/21186414/5d10a042-373a-4af0-b117-6e07da8ea0bc)
 3. 제목을 클릭하면 오류 발생
![image](https://github.com/eGovFramework/egovframe-common-components/assets/21186414/b8fe9e35-0a29-4af6-b34d-fd67400116b3)
 4. 이클립스 오류 내용
![image](https://github.com/eGovFramework/egovframe-common-components/assets/21186414/a3294429-6b49-46ea-a6b4-b1cf5c8f21c6)

### 환경정보 Environmental Information

 - OS정보 Operating System: Windows11
 - 표준프레임워크 버전 eGovFrame Version: 4.1
 - JDK(JRE) 정보: jdk8
 - WAS 정보: Tomcat 8.5.84
 - DB 정보: Mysql
 - 기타 환경 정보 Other environmental information:

### 어느 브라우저를 사용했나요? Which browser did you use?

Chrome

### 에러 로그 Error Logs

```shell
오류내용

Caused by: java.sql.SQLFeatureNotSupportedException: resultSet=net.sf.log4jdbc.ResultSetSpy@4a610edc, columnLabel=SBSCRB_DE, type=class java.time.LocalDateTime
	at org.apache.commons.dbcp2.Jdbc41Bridge.getObject(Jdbc41Bridge.java:336) ~[commons-dbcp2-2.9.0.jar:2.9.0]
	at org.apache.commons.dbcp2.DelegatingResultSet.getObject(DelegatingResultSet.java:773) ~[commons-dbcp2-2.9.0.jar:2.9.0]
	at org.apache.commons.dbcp2.Jdbc41Bridge.getObject(Jdbc41Bridge.java:266) ~[commons-dbcp2-2.9.0.jar:2.9.0]
	at org.apache.commons.dbcp2.DelegatingResultSet.getObject(DelegatingResultSet.java:773) ~[commons-dbcp2-2.9.0.jar:2.9.0]
	at org.apache.ibatis.type.LocalDateTimeTypeHandler.getNullableResult(LocalDateTimeTypeHandler.java:38) ~[mybatis-3.5.10.jar:3.5.10]
	at org.apache.ibatis.type.LocalDateTimeTypeHandler.getNullableResult(LocalDateTimeTypeHandler.java:28) ~[mybatis-3.5.10.jar:3.5.10]
	at org.apache.ibatis.type.BaseTypeHandler.getResult(BaseTypeHandler.java:85) ~[mybatis-3.5.10.jar:3.5.10]
	at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.applyAutomaticMappings(DefaultResultSetHandler.java:572) ~[mybatis-3.5.10.jar:3.5.10]
	at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.getRowValue(DefaultResultSetHandler.java:409) ~[mybatis-3.5.10.jar:3.5.10]
	at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.handleRowValuesForSimpleResultMap(DefaultResultSetHandler.java:361) ~[mybatis-3.5.10.jar:3.5.10]
	at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.handleRowValues(DefaultResultSetHandler.java:335) ~[mybatis-3.5.10.jar:3.5.10]
	at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.handleResultSet(DefaultResultSetHandler.java:308) ~[mybatis-3.5.10.jar:3.5.10]
	at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.handleResultSets(DefaultResultSetHandler.java:201) ~[mybatis-3.5.10.jar:3.5.10]
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.query(PreparedStatementHandler.java:65) ~[mybatis-3.5.10.jar:3.5.10]
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.query(RoutingStatementHandler.java:79) ~[mybatis-3.5.10.jar:3.5.10]
	at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:63) ~[mybatis-3.5.10.jar:3.5.10]
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:325) ~[mybatis-3.5.10.jar:3.5.10]
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156) ~[mybatis-3.5.10.jar:3.5.10]
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:109) ~[mybatis-3.5.10.jar:3.5.10]
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:89) ~[mybatis-3.5.10.jar:3.5.10]
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:151) ~[mybatis-3.5.10.jar:3.5.10]
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:145) ~[mybatis-3.5.10.jar:3.5.10]
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:140) ~[mybatis-3.5.10.jar:3.5.10]
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectOne(DefaultSqlSession.java:76) ~[mybatis-3.5.10.jar:3.5.10]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_302]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_302]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_302]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_302]
```
```

**Comment by eGovFrameSupport** [comment]
표준프레임워크 발전을 위한 소중한 의견 감사 드립니다.
