### ISSUE TITLE
[Bug]: 온라인POLL관리 상세조회 데이터 처리 에러

### ISSUE THREAD

**Issue by JHGONG113** [eGovFramework/egovframe-common-components#263]
### 연락처 Contact

jhgong113@gmail.com

### 오류 내용 Error Description

오류를 발견했어요. I found an error.
온라인POLL 관리목록에서 등록된 온라인POLL 을 클릭시에 데이터 처리 에러 오류 출력

### 오류 재현 방법 How to reproduce the error

(다음은 예시이며, 내용을 덮어 써 주세요. The following is an example, please overwrite the content.)

 1. 661.온라인POLL 관리 목록을 클릭한다.
 
![image](https://github.com/eGovFramework/egovframe-common-components/assets/131833924/60fb7b80-2257-4e5a-bdb2-24bc9160f30d)

2. 등록 버튼을 눌러 온라인 POLL을 등록한다.
 
![image](https://github.com/eGovFramework/egovframe-common-components/assets/131833924/582d756a-3cbd-42d6-83b8-8492aba7a31d)

 3. 등록 후 등록된 온라인 POLL 제목을 클릭한다,
 
![image](https://github.com/eGovFramework/egovframe-common-components/assets/131833924/24965ea3-0877-41e5-8822-5d4d3d56833e)

4. 이클립스 오류 내용 

![image](https://github.com/eGovFramework/egovframe-common-components/assets/131833924/8abf152d-63b7-4cb8-81ce-5d5a6a944020)

5. 오류 수정 방법

```sql
	<select id="selectOnlinePollItem" resultType="egovMap">
	 
		SELECT 
		POLL_ID,
		POLL_IEM_ID,
		POLL_IEM_NM,
		FRST_REGISTER_ID,
		DATE_FORMAT(FRST_REGIST_PNTTM,'%Y-%m-%d') AS FRST_REGIST_PNTTM,
		LAST_UPDUSR_ID,
		LAST_UPDT_PNTTM <-- 해당 라인 삭제
		DATE_FORMAT(LAST_UPDT_PNTTM,'%Y-%m-%d') AS LAST_UPDT_PNTTM
		FROM COMTNONLINEPOLLIEM
		WHERE 1=1
		AND POLL_ID = #{pollId} 
		ORDER BY POLL_IEM_NM DESC
	 
	</select>
```

### 환경정보 Environmental Information

 - OS정보 Operating System:  Window 11
 - 표준프레임워크 버전 eGovFrame Version:  4.1.0
 - JDK(JRE) 정보:  JDK8
 - WAS 정보:  tomcat 8.5
 - DB 정보:  mysql
 - 기타 환경 정보 Other environmental information:

### 어느 브라우저를 사용했나요? Which browser did you use?

Chrome

### 에러 로그 Error Logs

```shell
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '(LAST_UPDT_PNTTM,'%Y-%m-%d') AS LAST_UPDT_PNTTM
		FROM COMTNONLINEPOLLIEM
		WHER' at line 9
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_202]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_202]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_202]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_202]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:403) ~[mysql-connector-java-5.1.49.jar:5.1.49]
	at com.mysql.jdbc.Util.getInstance(Util.java:386) ~[mysql-connector-java-5.1.49.jar:5.1.49]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944) ~[mysql-connector-java-5.1.49.jar:5.1.49]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3933) ~[mysql-connector-java-5.1.49.jar:5.1.49]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3869) ~[mysql-connector-java-5.1.49.jar:5.1.49]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524) ~[mysql-connector-java-5.1.49.jar:5.1.49]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2675) ~[mysql-connector-java-5.1.49.jar:5.1.49]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2465) ~[mysql-connector-java-5.1.49.jar:5.1.49]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1915) ~[mysql-connector-java-5.1.49.jar:5.1.49]
	at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1254) ~[mysql-connector-java-5.1.49.jar:5.1.49]
	at net.sf.log4jdbc.PreparedStatementSpy.execute(PreparedStatementSpy.java:417) ~[log4jdbc-1.2.jar:?]
	at org.apache.commons.dbcp2.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:94) ~[commons-dbcp2-2.9.0.jar:2.9.0]
	at org.apache.commons.dbcp2.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:94) ~[commons-dbcp2-2.9.0.jar:2.9.0]
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.query(PreparedStatementHandler.java:64) ~[mybatis-3.5.10.jar:3.5.10]
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.query(RoutingStatementHandler.java:79) ~[mybatis-3.5.10.jar:3.5.10]
	at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:63) ~[mybatis-3.5.10.jar:3.5.10]
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:325) ~[mybatis-3.5.10.jar:3.5.10]
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156) ~[mybatis-3.5.10.jar:3.5.10]
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:109) ~[mybatis-3.5.10.jar:3.5.10]
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:89) ~[mybatis-3.5.10.jar:3.5.10]
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:151) ~[mybatis-3.5.10.jar:3.5.10]
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:145) ~[mybatis-3.5.10.jar:3.5.10]
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:140) ~[mybatis-3.5.10.jar:3.5.10]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_202]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_202]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_202]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_202]
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:427) ~[mybatis-spring-2.0.7.jar:2.0.7]
	... 139 more
```

**Comment by eGovFrameSupport** [comment]
[2023 전자정부 표준프레임워크 컨트리뷰션 참가 기념품 발송안내]

안녕하세요
전자정부 표준프레임워크 센터입니다.

'23년 4월 10일부터 8월 31일까지 약 4개월간, 전자정부 서비스 개발 표준 기반인 "전자정부 표준프레임워크" 개선에 민간 SW개발자의 아이디어와 의견을 반영하기 위해 "2023 전자정부 표준프레임워크 컨트리뷰션"을 실시 하였습니다.

표준프레임워크 깃허브(github.com/egovframework)에 보내주신 귀하의 의견에 감사드리며, 전자정부 표준프레임워크 운영·개선 과정에서 유용하게 활용토록 하겠습니다.
본 설문에 응답 주시면 표준프레임워크에서 마련한 소정의 기념품을 발송 드릴 예정이오니, 문항에 빠짐없이 응답 해 주시기 바랍니다.
아래의 URL을 통하여 설문지로 이동, 항목에 응답 부탁드립니다.

https://forms.gle/g5cKfG5rnNrqvqjaA

앞으로도 전자정부 표준프레임워크에 지속적인 관심 부탁드립니다.

※ 센터에서 준비한 감사장과 표준프레임워크 오픈커뮤니티에서 소정의 기념품을 택배 배송 해 드립니다.
※ 컨트리뷰션 종료 후, 시상 관련하여 연락 갈 예정이오니, 꼭 통화 가능한 본인번호를 기재해 주시기 바랍니다.
※ 귀하께서 답변해 주시는 내용은 컨트리뷰션 참가 확인 및 기념품 발송 목적으로만 활용되며, 개인정보는 기념품 발송 후 즉시 영구 삭제처리 됩니다.

감사합니다.

**Comment by eGovFrameSupport** [comment]
해당 오류는 함께 요청 주신 #264 PR에서 수정 코드가 반영 되었습니다.
표준프레임워크 발전을 위한 소중한 의견 감사 드립니다.
